const quotes = [
    "Remember, you are not alone.",
    "You are stronger than you think.",
    "Believe in yourself and your ability to overcome challenges.",
    "There is always hope. Keep moving forward.",
    "Small steps can lead to big changes.",
    "Be kind to yourself.",
    "You matter.",
    "You are capable of achieving anything you set your mind to.",
    "You are worthy of love, happiness, and success.",
    "You are unique and special in your own way.",
    "You have the power to create a positive impact on the world.",
    "You are surrounded by people who love and support you.",
    "You are growing and learning every day.",
    "You are resilient and can overcome any obstacle.",
    "You are becoming more confident and self-assured.",
    "You are attracting positive experiences into your life.",
    "You are living in abundance and prosperity.",
    "You are radiating positive energy and attracting positive people.",
    "You are filled with inner peace and tranquility.",
    "You are in control of your thoughts and emotions.",
    "You are open to receiving love and kindness.",
    "You are courageous and face challenges with strength.",
    "You are open to receiving all the good that life has to offer.",
    "You are surrounded by positive energy and loving vibrations.",
    "You are confident in your ability to make wise decisions.",
    "You trust in the process of life and surrender to its flow.",
    "You are a source of inspiration for others.",
    "You are grateful for your unique qualities and talents.",
    "You attract financial abundance with ease.",
    "You are constantly attracting new and exciting opportunities.",
    "You are living a life of purpose and meaning.",
    "You are making a difference in the world.",
    "You are loved and appreciated.",
    "You are worthy of everything you desire.",
    "You are capable of anything you dream of.",
    "You are amazing just the way you are.",
    "You are loved unconditionally.",
    "You are capable of great things.",
    "You are worthy of happiness.",
    "You are stronger than you think.",
    "You are capable of overcoming any challenge.",
    "You are never alone.",
    "There is always hope.",
    "You are capable of achieving your goals.",
    "You are loved and supported.",
    "You are capable of great things.",
    "You are worthy of happiness and success.",
    "You are stronger than you think.",
    "You are capable of overcoming any challenge.",
    "You are never alone.",
    "There is always hope.",
    "You are capable of achieving your goals.",
    "You are loved and supported.",
    "You are capable of great things.",
    "You are worthy of happiness and success.",
    "You are stronger than you think.",
    "You are capable of overcoming any challenge.",
  ];
  
  const quoteButton = document.getElementById('quoteButton');
  const quoteBox = document.getElementById('quoteBox');
  
    quoteButton.addEventListener('click', () => {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];
    quoteBox.textContent = randomQuote;
  });
